getStart/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('contact', views.contactView, name='contact'),
]

mainApp/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.index, name='index')
]

su/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainApp.urls')),
    path('getstart/', include('getStart.urls'))
]

getStart/models.py
from django.db import models

# Create your models here.

mainApp/models.py
from django.db import models

# Create your models here.

getStart/views.py
from django.shortcuts import render
from django import forms
from django.http import HttpResponse
from django.core.mail import send_mail, BadHeaderError


# Create your views here.

def index(request):
    return render(request, 'getStart/getStartIndex.html')

class ContactForm(forms.Form):
    name    = forms.CharField(max_length = 100)
    subject = forms.CharField()
    sender  = forms.CharField()
    message = forms.CharField()

    
def contactView(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            subject = form.cleaned_data['subject']
            sender = 'arbi.tularov1@yandex.ru' #form.cleaned_data['sender']
            message = "Name: {}, WeChat: {}, Email: {}".format(form.cleaned_data['name'], form.cleaned_data['message'], form.cleaned_data['sender'])

            recipients = ['arbi.tularov@yandex.ru', 'vizamv@qq.com']

            send_mail(subject, message, 'arbi.tularov1@yandex.ru', recipients)
            return render(request, 'getStart/thanks.html')
    else:
        form = ContactForm()
        return render(request, 'mainApp/index.html')

mainApp/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    return render(request, 'mainApp/index.html')

getStart/templates/getStart/getStartIndex.html
<!DOCTYPE html>
{% load static %}
<head>
	<title>Get Started </title>

    <link rel="shortcut icon" href="images/favicon.png" />

    <!-- Meta Tags -->
    <meta charset="utf-8">
    <meta name="description" content="Quqing | Time to take the next step">
    <meta name="author" content="#">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Theme Styles -->
  <!-- Bootstrap CSS CDN -->
    <!-- Bootstrap CSS CDN -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <link rel="stylesheet" href="{% static "min.style.css" %}">
    <!-- Font Awesome JS -->
</head>
<body>

<nav class="navbar-dark bg-dark main-navbar">
  <div class="container">
    <a class="navbar-brand " href="/"><img class="logo-main-bar" src="{% static "logo.png" %} " alt="logo"></a>
  </div>
</nav>



<section class="contacts-section">
  <div class="container">
    <div class="row">
      <div class="col-12 col-sm-12 col-md-10 col-lg-6 form-center">
        <div class="col-12 text-center">
          <h1 class="contact-text">Contacts</h2>
        </div>
        <form action="contact" method="post">{% csrf_token %}
          {{ form.non_field_errors }}
          <div>
            <label for="id_name">Name*</label>
            <input class="form-control text-muted custom-f-control" id="id_name" type="text" name="name"
              placeholder="Enter your name" required>
            {{ form.name.errors }}
            {{ form.name }}
          </div>
          <div>
            <label for="id_subject">Phone Number*</label>
            <input class="form-control text-muted custom-f-control" id="id_subject" type="text" name="subject"
              placeholder="Enter phone number" required>
            {{ form.subject.errors }}
            {{ form.subject }}
          </div>
          <div>
            <label for="id_sender">Email address*</label>
            <input class="form-control text-muted custom-f-control" id="id_sender" type="text" name="sender"
              placeholder="Enter email address" required>
            {{ form.sender.errors }}
            {{ form.sender }}
          </div>
          <div>
            <label for="id_message">Wechat*</label>
            <input class="form-control text-muted custom-f-control" id="id_message" type="text" name="message"
              placeholder="Enter Wechat ID" required>
            {{ form.message.errors }}
            {{ form.message }}
          </div>
          <div class="form-button text-center">
            <button type="submit" class="send">Send</button>
          </div>
        </form>

      </div>
    </div>
  </div>
</section>

<footer class="page-footer bg-dark mainfooter">

    <!-- Footer Elements -->
    <div class="container">
      <div class="row align-items-end footer-col">
        <div class="col-12 col-sm-12 col-md-6 col-lg-6 f-col1">
          <p>
            China, Heilongjiang, Harbin, <br>
            QUNLI 4th road, HUIZHI GUANGCHANG,
            9th floor
          </p>
        </div>

        <div class="col-12 col-sm-12 col-md-6 col-lg-6 f-col2">
          <p>
            <a class="email" href="mailto:Vizamv@qq.com">Vizamv@qq.com</a><br>
            tel: 13611204074
          </p>
        </div>
      </div>
    </div>
    <!-- Footer Elements -->
  <hr class="f-hr">
    <!-- Copyright -->
    <div class="container copyright-div text-center">© 2019 Copyright:<a href="/"> su-studio.art</a>
    </div>
    <!-- Copyright -->
  
  </footer>
      <!-- Footer -->
 
      <!-- Yandex.Metrika counter -->
<script type="text/javascript" >
  (function(m,e,t,r,i,k,a){m[i]=m[i]||function(){(m[i].a=m[i].a||[]).push(arguments)};
  m[i].l=1*new Date();k=e.createElement(t),a=e.getElementsByTagName(t)[0],k.async=1,k.src=r,a.parentNode.insertBefore(k,a)})
  (window, document, "script", "https://mc.yandex.ru/metrika/tag.js", "ym");

  ym(54532759, "init", {
       clickmap:true,
       trackLinks:true,
       accurateTrackBounce:true
  });
</script>
<noscript><div><img src="https://mc.yandex.ru/watch/54532759" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
<!-- /Yandex.Metrika counter -->

</body>
</html>

getStart/templates/getStart/thanks.html
<!DOCTYPE html>
{% load static %}
<head>
	<title>Thank You </title>
    <link rel="shortcut icon" href="images/favicon.png" />
    <!-- Meta Tags -->
    <meta charset="utf-8">
    <meta name="description" content="Quqing | Time to take the next step">
    <meta name="author" content="Henoc Essi">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Theme Styles -->
  <!-- Bootstrap CSS CDN -->
    <!-- Bootstrap CSS CDN -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="{% static "min.style.css" %}">
    <!-- Font Awesome JS -->
    <script type="js/navbar.js"></script>
</head>
<body>

<nav class="navbar-dark bg-dark main-navbar">
  <div class="container">
    <a class="navbar-brand " href="/"><img class="logo-main-bar" src="{% static "logo.png" %} " alt="logo"></a>
  </div>
</nav>

<div class="container">
    <div class="row">
        <div class="col-md-12 text-center content">
            <h2 class="main-h"> Thank you!</h2>
            <p class=return-home ><a href="/">Home</a></p>
        </div>
    </div>
</div>

</body>
</html>